all:
  hosts: 
    master:
      ansible_host: 46.21.245.88
      ip: 10.10.1.16
      access_ip: 46.21.245.88
      ansible_user: ubuntu
    worker-1:
      ansible_host: 89.169.168.72
      ip: 10.10.2.11
      access_ip: 89.169.168.72
      ansible_user: ubuntu
    worker-2:
      ansible_host: 158.160.144.69
      ip: 10.10.3.25
      access_ip: 158.160.144.69
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts: 
        master:

    kube_node:
      hosts: 
        worker-1:
        worker-2:

    etcd:
      hosts: 
        master:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}